import type { NextPage } from 'next'
import Head from 'next/head'

const Home: React.FC<NextPage> = () => {
	return (
		<div>
			<Head>
				<title>Badger</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
		</div>
	)
}

export default Home
